# Generated by Django 5.0.2 on 2024-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('risk_preference', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('annual_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_focus', models.CharField(help_text='Areas of interest for investment', max_length=255)),
            ],
        ),
    ]
